// small_tree: base class to handle reduced tree ntuples
// File generated with generate_small_tree.exe

#ifndef H_SMALL_TREE
#define H_SMALL_TREE

#include <vector>
#include <string>

#include "TTree.h"
#include "TChain.h"
#include "TTreeFormula.h"

class small_tree{
public:
  small_tree(); // Constructor to create tree
  small_tree(const std::string &filename); // Constructor to read tree

  int Add(const std::string &filename);
  long GetEntries() const;
  virtual void GetEntry(const long entry);
  float GetBranchValue(TString branch);
  bool PassString(TString cut);

  virtual void Fill();
  void Write();

  virtual std::string Type() const;

  static const double bad_val_;

  virtual ~small_tree();

  float  const & ht() const;
  float  & ht();
  float  const & met() const;
  float  & met();
  float  const & met_phi() const;
  float  & met_phi();
  float  const & mht() const;
  float  & mht();
  float  const & mj() const;
  float  & mj();
  float  const & mj08() const;
  float  & mj08();
  float  const & mt() const;
  float  & mt();
  float  const & ntrupv_mean() const;
  float  & ntrupv_mean();
  float  const & weight() const;
  float  & weight();
  int  const & event() const;
  int  & event();
  int  const & lumiblock() const;
  int  & lumiblock();
  int  const & nbl() const;
  int  & nbl();
  int  const & nbm() const;
  int  & nbm();
  int  const & nbt() const;
  int  & nbt();
  int  const & nels() const;
  int  & nels();
  int  const & nfjets() const;
  int  & nfjets();
  int  const & nfjets08() const;
  int  & nfjets08();
  int  const & njets() const;
  int  & njets();
  int  const & nleps() const;
  int  & nleps();
  int  const & nmus() const;
  int  & nmus();
  int  const & npv() const;
  int  & npv();
  int  const & ntruels() const;
  int  & ntruels();
  int  const & ntruleps() const;
  int  & ntruleps();
  int  const & ntrumus() const;
  int  & ntrumus();
  int  const & ntrupv() const;
  int  & ntrupv();
  int  const & ntrutaush() const;
  int  & ntrutaush();
  int  const & ntrutausl() const;
  int  & ntrutausl();
  int  const & nvels() const;
  int  & nvels();
  int  const & nvmus() const;
  int  & nvmus();
  int  const & run() const;
  int  & run();
  std::vector<bool>  const & els_ispf() const;
  std::vector<bool>  & els_ispf();
  std::vector<bool>  const & els_sigid() const;
  std::vector<bool>  & els_sigid();
  std::vector<bool>  const & jets_islep() const;
  std::vector<bool>  & jets_islep();
  std::vector<bool>  const & mus_sigid() const;
  std::vector<bool>  & mus_sigid();
  std::vector<float>  const & els_d0() const;
  std::vector<float>  & els_d0();
  std::vector<float>  const & els_dz() const;
  std::vector<float>  & els_dz();
  std::vector<float>  const & els_eta() const;
  std::vector<float>  & els_eta();
  std::vector<float>  const & els_phi() const;
  std::vector<float>  & els_phi();
  std::vector<float>  const & els_pt() const;
  std::vector<float>  & els_pt();
  std::vector<float>  const & els_sceta() const;
  std::vector<float>  & els_sceta();
  std::vector<float>  const & fjets08_eta() const;
  std::vector<float>  & fjets08_eta();
  std::vector<float>  const & fjets08_m() const;
  std::vector<float>  & fjets08_m();
  std::vector<float>  const & fjets08_phi() const;
  std::vector<float>  & fjets08_phi();
  std::vector<float>  const & fjets08_poscsv() const;
  std::vector<float>  & fjets08_poscsv();
  std::vector<float>  const & fjets08_pt() const;
  std::vector<float>  & fjets08_pt();
  std::vector<float>  const & fjets08_sumcsv() const;
  std::vector<float>  & fjets08_sumcsv();
  std::vector<float>  const & fjets_eta() const;
  std::vector<float>  & fjets_eta();
  std::vector<float>  const & fjets_m() const;
  std::vector<float>  & fjets_m();
  std::vector<float>  const & fjets_phi() const;
  std::vector<float>  & fjets_phi();
  std::vector<float>  const & fjets_poscsv() const;
  std::vector<float>  & fjets_poscsv();
  std::vector<float>  const & fjets_pt() const;
  std::vector<float>  & fjets_pt();
  std::vector<float>  const & fjets_sumcsv() const;
  std::vector<float>  & fjets_sumcsv();
  std::vector<float>  const & jets_csv() const;
  std::vector<float>  & jets_csv();
  std::vector<float>  const & jets_eta() const;
  std::vector<float>  & jets_eta();
  std::vector<float>  const & jets_m() const;
  std::vector<float>  & jets_m();
  std::vector<float>  const & jets_phi() const;
  std::vector<float>  & jets_phi();
  std::vector<float>  const & jets_pt() const;
  std::vector<float>  & jets_pt();
  std::vector<float>  const & mus_d0() const;
  std::vector<float>  & mus_d0();
  std::vector<float>  const & mus_dz() const;
  std::vector<float>  & mus_dz();
  std::vector<float>  const & mus_eta() const;
  std::vector<float>  & mus_eta();
  std::vector<float>  const & mus_phi() const;
  std::vector<float>  & mus_phi();
  std::vector<float>  const & mus_pt() const;
  std::vector<float>  & mus_pt();
  std::vector<int>  const & els_charge() const;
  std::vector<int>  & els_charge();
  std::vector<int>  const & fjets08_btags() const;
  std::vector<int>  & fjets08_btags();
  std::vector<int>  const & fjets08_nconst() const;
  std::vector<int>  & fjets08_nconst();
  std::vector<int>  const & fjets_btags() const;
  std::vector<int>  & fjets_btags();
  std::vector<int>  const & fjets_nconst() const;
  std::vector<int>  & fjets_nconst();
  std::vector<int>  const & jets_fjet08_index() const;
  std::vector<int>  & jets_fjet08_index();
  std::vector<int>  const & jets_fjet_index() const;
  std::vector<int>  & jets_fjet_index();
  std::vector<int>  const & mus_charge() const;
  std::vector<int>  & mus_charge();

  __attribute__((noreturn)) virtual bool  const & pass() const;
  __attribute__((noreturn)) virtual bool  & pass();
  __attribute__((noreturn)) virtual float  const & dphi_neutralinos() const;
  __attribute__((noreturn)) virtual float  & dphi_neutralinos();
  __attribute__((noreturn)) virtual float  const & dphi_wlep() const;
  __attribute__((noreturn)) virtual float  & dphi_wlep();
  __attribute__((noreturn)) virtual float  const & dphi_wlep_reliso() const;
  __attribute__((noreturn)) virtual float  & dphi_wlep_reliso();
  __attribute__((noreturn)) virtual float  const & eff_trig() const;
  __attribute__((noreturn)) virtual float  & eff_trig();
  __attribute__((noreturn)) virtual float  const & gen_ht() const;
  __attribute__((noreturn)) virtual float  & gen_ht();
  __attribute__((noreturn)) virtual float  const & gen_met() const;
  __attribute__((noreturn)) virtual float  & gen_met();
  __attribute__((noreturn)) virtual float  const & gen_met_phi() const;
  __attribute__((noreturn)) virtual float  & gen_met_phi();
  __attribute__((noreturn)) virtual float  const & gen_mj() const;
  __attribute__((noreturn)) virtual float  & gen_mj();
  __attribute__((noreturn)) virtual float  const & ht40() const;
  __attribute__((noreturn)) virtual float  & ht40();
  __attribute__((noreturn)) virtual float  const & ht_isr() const;
  __attribute__((noreturn)) virtual float  & ht_isr();
  __attribute__((noreturn)) virtual float  const & ht_isr_me() const;
  __attribute__((noreturn)) virtual float  & ht_isr_me();
  __attribute__((noreturn)) virtual float  const & ht_isr_nonme() const;
  __attribute__((noreturn)) virtual float  & ht_isr_nonme();
  __attribute__((noreturn)) virtual float  const & ht_isr_tru() const;
  __attribute__((noreturn)) virtual float  & ht_isr_tru();
  __attribute__((noreturn)) virtual float  const & ht_nonb() const;
  __attribute__((noreturn)) virtual float  & ht_nonb();
  __attribute__((noreturn)) virtual float  const & ht_reliso() const;
  __attribute__((noreturn)) virtual float  & ht_reliso();
  __attribute__((noreturn)) virtual float  const & ht_sub() const;
  __attribute__((noreturn)) virtual float  & ht_sub();
  __attribute__((noreturn)) virtual float  const & lep_eta() const;
  __attribute__((noreturn)) virtual float  & lep_eta();
  __attribute__((noreturn)) virtual float  const & lep_eta_reliso() const;
  __attribute__((noreturn)) virtual float  & lep_eta_reliso();
  __attribute__((noreturn)) virtual float  const & lep_phi() const;
  __attribute__((noreturn)) virtual float  & lep_phi();
  __attribute__((noreturn)) virtual float  const & lep_phi_reliso() const;
  __attribute__((noreturn)) virtual float  & lep_phi_reliso();
  __attribute__((noreturn)) virtual float  const & lep_pt() const;
  __attribute__((noreturn)) virtual float  & lep_pt();
  __attribute__((noreturn)) virtual float  const & lep_pt_reliso() const;
  __attribute__((noreturn)) virtual float  & lep_pt_reliso();
  __attribute__((noreturn)) virtual float  const & max_dphi_bb() const;
  __attribute__((noreturn)) virtual float  & max_dphi_bb();
  __attribute__((noreturn)) virtual float  const & max_dphi_blep() const;
  __attribute__((noreturn)) virtual float  & max_dphi_blep();
  __attribute__((noreturn)) virtual float  const & max_dphi_bmet() const;
  __attribute__((noreturn)) virtual float  & max_dphi_bmet();
  __attribute__((noreturn)) virtual float  const & max_dr_bb() const;
  __attribute__((noreturn)) virtual float  & max_dr_bb();
  __attribute__((noreturn)) virtual float  const & max_dr_blep() const;
  __attribute__((noreturn)) virtual float  & max_dr_blep();
  __attribute__((noreturn)) virtual float  const & max_m_bb() const;
  __attribute__((noreturn)) virtual float  & max_m_bb();
  __attribute__((noreturn)) virtual float  const & max_m_blep() const;
  __attribute__((noreturn)) virtual float  & max_m_blep();
  __attribute__((noreturn)) virtual float  const & max_mt_bmet() const;
  __attribute__((noreturn)) virtual float  & max_mt_bmet();
  __attribute__((noreturn)) virtual float  const & max_pt_bb() const;
  __attribute__((noreturn)) virtual float  & max_pt_bb();
  __attribute__((noreturn)) virtual float  const & max_pt_blep() const;
  __attribute__((noreturn)) virtual float  & max_pt_blep();
  __attribute__((noreturn)) virtual float  const & max_pt_bmet() const;
  __attribute__((noreturn)) virtual float  & max_pt_bmet();
  __attribute__((noreturn)) virtual float  const & mht_sub() const;
  __attribute__((noreturn)) virtual float  & mht_sub();
  __attribute__((noreturn)) virtual float  const & min_dphi_bb() const;
  __attribute__((noreturn)) virtual float  & min_dphi_bb();
  __attribute__((noreturn)) virtual float  const & min_dphi_blep() const;
  __attribute__((noreturn)) virtual float  & min_dphi_blep();
  __attribute__((noreturn)) virtual float  const & min_dphi_bmet() const;
  __attribute__((noreturn)) virtual float  & min_dphi_bmet();
  __attribute__((noreturn)) virtual float  const & min_dr_bb() const;
  __attribute__((noreturn)) virtual float  & min_dr_bb();
  __attribute__((noreturn)) virtual float  const & min_dr_blep() const;
  __attribute__((noreturn)) virtual float  & min_dr_blep();
  __attribute__((noreturn)) virtual float  const & min_m_bb() const;
  __attribute__((noreturn)) virtual float  & min_m_bb();
  __attribute__((noreturn)) virtual float  const & min_m_blep() const;
  __attribute__((noreturn)) virtual float  & min_m_blep();
  __attribute__((noreturn)) virtual float  const & min_mt_bmet() const;
  __attribute__((noreturn)) virtual float  & min_mt_bmet();
  __attribute__((noreturn)) virtual float  const & min_mt_bmet_with_w_mass() const;
  __attribute__((noreturn)) virtual float  & min_mt_bmet_with_w_mass();
  __attribute__((noreturn)) virtual float  const & min_pt_bb() const;
  __attribute__((noreturn)) virtual float  & min_pt_bb();
  __attribute__((noreturn)) virtual float  const & min_pt_blep() const;
  __attribute__((noreturn)) virtual float  & min_pt_blep();
  __attribute__((noreturn)) virtual float  const & min_pt_bmet() const;
  __attribute__((noreturn)) virtual float  & min_pt_bmet();
  __attribute__((noreturn)) virtual float  const & mindphin_metjet() const;
  __attribute__((noreturn)) virtual float  & mindphin_metjet();
  __attribute__((noreturn)) virtual float  const & mj15() const;
  __attribute__((noreturn)) virtual float  & mj15();
  __attribute__((noreturn)) virtual float  const & mj_sub() const;
  __attribute__((noreturn)) virtual float  & mj_sub();
  __attribute__((noreturn)) virtual float  const & mt_reliso() const;
  __attribute__((noreturn)) virtual float  & mt_reliso();
  __attribute__((noreturn)) virtual float  const & st() const;
  __attribute__((noreturn)) virtual float  & st();
  __attribute__((noreturn)) virtual float  const & st_reliso() const;
  __attribute__((noreturn)) virtual float  & st_reliso();
  __attribute__((noreturn)) virtual float  const & tru_gluglu_dphi() const;
  __attribute__((noreturn)) virtual float  & tru_gluglu_dphi();
  __attribute__((noreturn)) virtual float  const & tru_gluglu_m() const;
  __attribute__((noreturn)) virtual float  & tru_gluglu_m();
  __attribute__((noreturn)) virtual float  const & tru_gluglu_pt() const;
  __attribute__((noreturn)) virtual float  & tru_gluglu_pt();
  __attribute__((noreturn)) virtual float  const & tru_gluglu_ptdiff() const;
  __attribute__((noreturn)) virtual float  & tru_gluglu_ptdiff();
  __attribute__((noreturn)) virtual float  const & tru_sphericity() const;
  __attribute__((noreturn)) virtual float  & tru_sphericity();
  __attribute__((noreturn)) virtual float  const & tru_tt_dphi() const;
  __attribute__((noreturn)) virtual float  & tru_tt_dphi();
  __attribute__((noreturn)) virtual float  const & tru_tt_m() const;
  __attribute__((noreturn)) virtual float  & tru_tt_m();
  __attribute__((noreturn)) virtual float  const & tru_tt_pt() const;
  __attribute__((noreturn)) virtual float  & tru_tt_pt();
  __attribute__((noreturn)) virtual float  const & tru_tt_ptdiff() const;
  __attribute__((noreturn)) virtual float  & tru_tt_ptdiff();
  __attribute__((noreturn)) virtual float  const & trutop1_phi() const;
  __attribute__((noreturn)) virtual float  & trutop1_phi();
  __attribute__((noreturn)) virtual float  const & trutop1_pt() const;
  __attribute__((noreturn)) virtual float  & trutop1_pt();
  __attribute__((noreturn)) virtual float  const & trutop2_phi() const;
  __attribute__((noreturn)) virtual float  & trutop2_phi();
  __attribute__((noreturn)) virtual float  const & trutop2_pt() const;
  __attribute__((noreturn)) virtual float  & trutop2_pt();
  __attribute__((noreturn)) virtual float  const & w_pu_rpv() const;
  __attribute__((noreturn)) virtual float  & w_pu_rpv();
  __attribute__((noreturn)) virtual int  const & lep_charge() const;
  __attribute__((noreturn)) virtual int  & lep_charge();
  __attribute__((noreturn)) virtual int  const & lep_charge_reliso() const;
  __attribute__((noreturn)) virtual int  & lep_charge_reliso();
  __attribute__((noreturn)) virtual int  const & n_isr_me() const;
  __attribute__((noreturn)) virtual int  & n_isr_me();
  __attribute__((noreturn)) virtual int  const & n_isr_nonme() const;
  __attribute__((noreturn)) virtual int  & n_isr_nonme();
  __attribute__((noreturn)) virtual int  const & nbadjets() const;
  __attribute__((noreturn)) virtual int  & nbadjets();
  __attribute__((noreturn)) virtual int  const & nbl40() const;
  __attribute__((noreturn)) virtual int  & nbl40();
  __attribute__((noreturn)) virtual int  const & nbl_sub() const;
  __attribute__((noreturn)) virtual int  & nbl_sub();
  __attribute__((noreturn)) virtual int  const & nbm40() const;
  __attribute__((noreturn)) virtual int  & nbm40();
  __attribute__((noreturn)) virtual int  const & nbm_sub() const;
  __attribute__((noreturn)) virtual int  & nbm_sub();
  __attribute__((noreturn)) virtual int  const & nbt40() const;
  __attribute__((noreturn)) virtual int  & nbt40();
  __attribute__((noreturn)) virtual int  const & nbt_sub() const;
  __attribute__((noreturn)) virtual int  & nbt_sub();
  __attribute__((noreturn)) virtual int  const & nels_reliso() const;
  __attribute__((noreturn)) virtual int  & nels_reliso();
  __attribute__((noreturn)) virtual int  const & nfjets15() const;
  __attribute__((noreturn)) virtual int  & nfjets15();
  __attribute__((noreturn)) virtual int  const & nfsubjets() const;
  __attribute__((noreturn)) virtual int  & nfsubjets();
  __attribute__((noreturn)) virtual int  const & ngenfjets() const;
  __attribute__((noreturn)) virtual int  & ngenfjets();
  __attribute__((noreturn)) virtual int  const & ngenjets() const;
  __attribute__((noreturn)) virtual int  & ngenjets();
  __attribute__((noreturn)) virtual int  const & njets40() const;
  __attribute__((noreturn)) virtual int  & njets40();
  __attribute__((noreturn)) virtual int  const & nleps_reliso() const;
  __attribute__((noreturn)) virtual int  & nleps_reliso();
  __attribute__((noreturn)) virtual int  const & nmus_reliso() const;
  __attribute__((noreturn)) virtual int  & nmus_reliso();
  __attribute__((noreturn)) virtual int  const & nsubjets() const;
  __attribute__((noreturn)) virtual int  & nsubjets();
  __attribute__((noreturn)) virtual int  const & ntks() const;
  __attribute__((noreturn)) virtual int  & ntks();
  __attribute__((noreturn)) virtual int  const & ntks_chg() const;
  __attribute__((noreturn)) virtual int  & ntks_chg();
  __attribute__((noreturn)) virtual int  const & ntks_chg_mini() const;
  __attribute__((noreturn)) virtual int  & ntks_chg_mini();
  __attribute__((noreturn)) virtual int  const & ntks_chg_reliso() const;
  __attribute__((noreturn)) virtual int  & ntks_chg_reliso();
  __attribute__((noreturn)) virtual int  const & ntrumeisr() const;
  __attribute__((noreturn)) virtual int  & ntrumeisr();
  __attribute__((noreturn)) virtual int  const & nvels_reliso() const;
  __attribute__((noreturn)) virtual int  & nvels_reliso();
  __attribute__((noreturn)) virtual int  const & nvmus_reliso() const;
  __attribute__((noreturn)) virtual int  & nvmus_reliso();
  __attribute__((noreturn)) virtual std::vector<bool>  const & badjets_islep() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & badjets_islep();
  __attribute__((noreturn)) virtual std::vector<bool>  const & els_tru_tm() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & els_tru_tm();
  __attribute__((noreturn)) virtual std::vector<bool>  const & mus_tru_tm() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & mus_tru_tm();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_from_tau() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_from_tau();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_from_tauhad() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_from_tauhad();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_from_taulep() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_from_taulep();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_from_w() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_from_w();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_is_primary() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_is_primary();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_is_primary_reliso() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_is_primary_reliso();
  __attribute__((noreturn)) virtual std::vector<bool>  const & tks_is_sig_lep() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & tks_is_sig_lep();
  __attribute__((noreturn)) virtual std::vector<bool>  const & trig() const;
  __attribute__((noreturn)) virtual std::vector<bool>  & trig();
  __attribute__((noreturn)) virtual std::vector<float>  const & badjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & badjets_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & badjets_id() const;
  __attribute__((noreturn)) virtual std::vector<float>  & badjets_id();
  __attribute__((noreturn)) virtual std::vector<float>  const & badjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & badjets_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & badjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & badjets_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & badjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & badjets_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & dr_bb() const;
  __attribute__((noreturn)) virtual std::vector<float>  & dr_bb();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_miniso_10() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_miniso_10();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_miniso_10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_miniso_10_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_miniso_tr10() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_miniso_tr10();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_miniso_tr10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_miniso_tr10_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_mt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_mt();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso_r01() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso_r01();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso_r015() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso_r015();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso_r02() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso_r02();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso_r03() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso_r03();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_reliso_r04() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_reliso_r04();
  __attribute__((noreturn)) virtual std::vector<float>  const & els_tru_dr() const;
  __attribute__((noreturn)) virtual std::vector<float>  & els_tru_dr();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_poscsv() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_poscsv();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & fjets15_sumcsv() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fjets15_sumcsv();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_poscsv() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_poscsv();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & fsubjets_sumcsv() const;
  __attribute__((noreturn)) virtual std::vector<float>  & fsubjets_sumcsv();
  __attribute__((noreturn)) virtual std::vector<float>  const & genfjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genfjets_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & genfjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genfjets_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & genfjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genfjets_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & genfjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genfjets_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & genjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genjets_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & genjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genjets_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & genjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genjets_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & genjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & genjets_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & glu_proj_frac() const;
  __attribute__((noreturn)) virtual std::vector<float>  & glu_proj_frac();
  __attribute__((noreturn)) virtual std::vector<float>  const & jets_gen_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & jets_gen_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & jets_id() const;
  __attribute__((noreturn)) virtual std::vector<float>  & jets_id();
  __attribute__((noreturn)) virtual std::vector<float>  const & jets_parton_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & jets_parton_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & jets_pt_from_mini() const;
  __attribute__((noreturn)) virtual std::vector<float>  & jets_pt_from_mini();
  __attribute__((noreturn)) virtual std::vector<float>  const & jets_pt_res() const;
  __attribute__((noreturn)) virtual std::vector<float>  & jets_pt_res();
  __attribute__((noreturn)) virtual std::vector<float>  const & mc_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mc_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & mc_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mc_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & mc_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mc_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_miniso_10() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_miniso_10();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_miniso_10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_miniso_10_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_miniso_tr10() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_miniso_tr10();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_miniso_tr10_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_miniso_tr10_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_mt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_mt();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso_r01() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso_r01();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso_r015() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso_r015();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso_r02() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso_r02();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso_r03() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso_r03();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_reliso_r04() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_reliso_r04();
  __attribute__((noreturn)) virtual std::vector<float>  const & mus_tru_dr() const;
  __attribute__((noreturn)) virtual std::vector<float>  & mus_tru_dr();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_csv() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_csv();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_id() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_id();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_m() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_m();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_mindr() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_mindr();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_subeta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_subeta();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_subm() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_subm();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_subphi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_subphi();
  __attribute__((noreturn)) virtual std::vector<float>  const & subjets_subpt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & subjets_subpt();
  __attribute__((noreturn)) virtual std::vector<float>  const & sys_bctag() const;
  __attribute__((noreturn)) virtual std::vector<float>  & sys_bctag();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_eta() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_eta();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_mini_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_mini_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_mini_ne() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_mini_ne();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_mt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_mt();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_phi() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_phi();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_pt() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_pt();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r02_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r02_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r02_ne() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r02_ne();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r03_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r03_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r03_ne() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r03_ne();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r04_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r04_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r04_ne() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r04_ne();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r05_ch() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r05_ch();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_r05_ne() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_r05_ne();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_tru_dp() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_tru_dp();
  __attribute__((noreturn)) virtual std::vector<float>  const & tks_tru_dr() const;
  __attribute__((noreturn)) virtual std::vector<float>  & tks_tru_dr();
  __attribute__((noreturn)) virtual std::vector<int>  const & els_tru_id() const;
  __attribute__((noreturn)) virtual std::vector<int>  & els_tru_id();
  __attribute__((noreturn)) virtual std::vector<int>  const & els_tru_momid() const;
  __attribute__((noreturn)) virtual std::vector<int>  & els_tru_momid();
  __attribute__((noreturn)) virtual std::vector<int>  const & fjets15_btags() const;
  __attribute__((noreturn)) virtual std::vector<int>  & fjets15_btags();
  __attribute__((noreturn)) virtual std::vector<int>  const & fjets15_nconst() const;
  __attribute__((noreturn)) virtual std::vector<int>  & fjets15_nconst();
  __attribute__((noreturn)) virtual std::vector<int>  const & fsubjets_btags() const;
  __attribute__((noreturn)) virtual std::vector<int>  & fsubjets_btags();
  __attribute__((noreturn)) virtual std::vector<int>  const & fsubjets_nconst() const;
  __attribute__((noreturn)) virtual std::vector<int>  & fsubjets_nconst();
  __attribute__((noreturn)) virtual std::vector<int>  const & genfjets_nconst() const;
  __attribute__((noreturn)) virtual std::vector<int>  & genfjets_nconst();
  __attribute__((noreturn)) virtual std::vector<int>  const & genjets_genfjet_index() const;
  __attribute__((noreturn)) virtual std::vector<int>  & genjets_genfjet_index();
  __attribute__((noreturn)) virtual std::vector<int>  const & genjets_isr_code() const;
  __attribute__((noreturn)) virtual std::vector<int>  & genjets_isr_code();
  __attribute__((noreturn)) virtual std::vector<int>  const & jets_fjet15_index() const;
  __attribute__((noreturn)) virtual std::vector<int>  & jets_fjet15_index();
  __attribute__((noreturn)) virtual std::vector<int>  const & jets_isr_code() const;
  __attribute__((noreturn)) virtual std::vector<int>  & jets_isr_code();
  __attribute__((noreturn)) virtual std::vector<int>  const & mc_id() const;
  __attribute__((noreturn)) virtual std::vector<int>  & mc_id();
  __attribute__((noreturn)) virtual std::vector<int>  const & mc_status() const;
  __attribute__((noreturn)) virtual std::vector<int>  & mc_status();
  __attribute__((noreturn)) virtual std::vector<int>  const & mus_tru_id() const;
  __attribute__((noreturn)) virtual std::vector<int>  & mus_tru_id();
  __attribute__((noreturn)) virtual std::vector<int>  const & mus_tru_momid() const;
  __attribute__((noreturn)) virtual std::vector<int>  & mus_tru_momid();
  __attribute__((noreturn)) virtual std::vector<int>  const & subjets_fsubjet_index() const;
  __attribute__((noreturn)) virtual std::vector<int>  & subjets_fsubjet_index();
  __attribute__((noreturn)) virtual std::vector<int>  const & subjets_nsub() const;
  __attribute__((noreturn)) virtual std::vector<int>  & subjets_nsub();
  __attribute__((noreturn)) virtual std::vector<int>  const & tks_charge() const;
  __attribute__((noreturn)) virtual std::vector<int>  & tks_charge();
  __attribute__((noreturn)) virtual std::vector<int>  const & tks_from_pv() const;
  __attribute__((noreturn)) virtual std::vector<int>  & tks_from_pv();
  __attribute__((noreturn)) virtual std::vector<int>  const & tks_id() const;
  __attribute__((noreturn)) virtual std::vector<int>  & tks_id();
  __attribute__((noreturn)) virtual std::vector<int>  const & tks_num_prongs() const;
  __attribute__((noreturn)) virtual std::vector<int>  & tks_num_prongs();
  __attribute__((noreturn)) virtual std::vector<int>  const & tks_tru_id() const;
  __attribute__((noreturn)) virtual std::vector<int>  & tks_tru_id();
  __attribute__((noreturn)) virtual std::vector<size_t>  const & mc_mom() const;
  __attribute__((noreturn)) virtual std::vector<size_t>  & mc_mom();
  __attribute__((noreturn)) virtual unsigned  const & mc_type() const;
  __attribute__((noreturn)) virtual unsigned  & mc_type();

protected:
  TChain chain_;
  TTree tree_;
  long entry_;
  const bool read_only_;

private:
  class VectorLoader{
  public:
    VectorLoader();
  private:
    static bool loaded_;
  };

  static VectorLoader vl_;
  float  ht_;
  TBranch *b_ht_;
  mutable bool c_ht_;
  float  met_;
  TBranch *b_met_;
  mutable bool c_met_;
  float  met_phi_;
  TBranch *b_met_phi_;
  mutable bool c_met_phi_;
  float  mht_;
  TBranch *b_mht_;
  mutable bool c_mht_;
  float  mj_;
  TBranch *b_mj_;
  mutable bool c_mj_;
  float  mj08_;
  TBranch *b_mj08_;
  mutable bool c_mj08_;
  float  mt_;
  TBranch *b_mt_;
  mutable bool c_mt_;
  float  ntrupv_mean_;
  TBranch *b_ntrupv_mean_;
  mutable bool c_ntrupv_mean_;
  float  weight_;
  TBranch *b_weight_;
  mutable bool c_weight_;
  int  event_;
  TBranch *b_event_;
  mutable bool c_event_;
  int  lumiblock_;
  TBranch *b_lumiblock_;
  mutable bool c_lumiblock_;
  int  nbl_;
  TBranch *b_nbl_;
  mutable bool c_nbl_;
  int  nbm_;
  TBranch *b_nbm_;
  mutable bool c_nbm_;
  int  nbt_;
  TBranch *b_nbt_;
  mutable bool c_nbt_;
  int  nels_;
  TBranch *b_nels_;
  mutable bool c_nels_;
  int  nfjets_;
  TBranch *b_nfjets_;
  mutable bool c_nfjets_;
  int  nfjets08_;
  TBranch *b_nfjets08_;
  mutable bool c_nfjets08_;
  int  njets_;
  TBranch *b_njets_;
  mutable bool c_njets_;
  int  nleps_;
  TBranch *b_nleps_;
  mutable bool c_nleps_;
  int  nmus_;
  TBranch *b_nmus_;
  mutable bool c_nmus_;
  int  npv_;
  TBranch *b_npv_;
  mutable bool c_npv_;
  int  ntruels_;
  TBranch *b_ntruels_;
  mutable bool c_ntruels_;
  int  ntruleps_;
  TBranch *b_ntruleps_;
  mutable bool c_ntruleps_;
  int  ntrumus_;
  TBranch *b_ntrumus_;
  mutable bool c_ntrumus_;
  int  ntrupv_;
  TBranch *b_ntrupv_;
  mutable bool c_ntrupv_;
  int  ntrutaush_;
  TBranch *b_ntrutaush_;
  mutable bool c_ntrutaush_;
  int  ntrutausl_;
  TBranch *b_ntrutausl_;
  mutable bool c_ntrutausl_;
  int  nvels_;
  TBranch *b_nvels_;
  mutable bool c_nvels_;
  int  nvmus_;
  TBranch *b_nvmus_;
  mutable bool c_nvmus_;
  int  run_;
  TBranch *b_run_;
  mutable bool c_run_;
  std::vector<bool>  els_ispf_;
  std::vector<bool>  *p_els_ispf_;
  TBranch *b_els_ispf_;
  mutable bool c_els_ispf_;
  std::vector<bool>  els_sigid_;
  std::vector<bool>  *p_els_sigid_;
  TBranch *b_els_sigid_;
  mutable bool c_els_sigid_;
  std::vector<bool>  jets_islep_;
  std::vector<bool>  *p_jets_islep_;
  TBranch *b_jets_islep_;
  mutable bool c_jets_islep_;
  std::vector<bool>  mus_sigid_;
  std::vector<bool>  *p_mus_sigid_;
  TBranch *b_mus_sigid_;
  mutable bool c_mus_sigid_;
  std::vector<float>  els_d0_;
  std::vector<float>  *p_els_d0_;
  TBranch *b_els_d0_;
  mutable bool c_els_d0_;
  std::vector<float>  els_dz_;
  std::vector<float>  *p_els_dz_;
  TBranch *b_els_dz_;
  mutable bool c_els_dz_;
  std::vector<float>  els_eta_;
  std::vector<float>  *p_els_eta_;
  TBranch *b_els_eta_;
  mutable bool c_els_eta_;
  std::vector<float>  els_phi_;
  std::vector<float>  *p_els_phi_;
  TBranch *b_els_phi_;
  mutable bool c_els_phi_;
  std::vector<float>  els_pt_;
  std::vector<float>  *p_els_pt_;
  TBranch *b_els_pt_;
  mutable bool c_els_pt_;
  std::vector<float>  els_sceta_;
  std::vector<float>  *p_els_sceta_;
  TBranch *b_els_sceta_;
  mutable bool c_els_sceta_;
  std::vector<float>  fjets08_eta_;
  std::vector<float>  *p_fjets08_eta_;
  TBranch *b_fjets08_eta_;
  mutable bool c_fjets08_eta_;
  std::vector<float>  fjets08_m_;
  std::vector<float>  *p_fjets08_m_;
  TBranch *b_fjets08_m_;
  mutable bool c_fjets08_m_;
  std::vector<float>  fjets08_phi_;
  std::vector<float>  *p_fjets08_phi_;
  TBranch *b_fjets08_phi_;
  mutable bool c_fjets08_phi_;
  std::vector<float>  fjets08_poscsv_;
  std::vector<float>  *p_fjets08_poscsv_;
  TBranch *b_fjets08_poscsv_;
  mutable bool c_fjets08_poscsv_;
  std::vector<float>  fjets08_pt_;
  std::vector<float>  *p_fjets08_pt_;
  TBranch *b_fjets08_pt_;
  mutable bool c_fjets08_pt_;
  std::vector<float>  fjets08_sumcsv_;
  std::vector<float>  *p_fjets08_sumcsv_;
  TBranch *b_fjets08_sumcsv_;
  mutable bool c_fjets08_sumcsv_;
  std::vector<float>  fjets_eta_;
  std::vector<float>  *p_fjets_eta_;
  TBranch *b_fjets_eta_;
  mutable bool c_fjets_eta_;
  std::vector<float>  fjets_m_;
  std::vector<float>  *p_fjets_m_;
  TBranch *b_fjets_m_;
  mutable bool c_fjets_m_;
  std::vector<float>  fjets_phi_;
  std::vector<float>  *p_fjets_phi_;
  TBranch *b_fjets_phi_;
  mutable bool c_fjets_phi_;
  std::vector<float>  fjets_poscsv_;
  std::vector<float>  *p_fjets_poscsv_;
  TBranch *b_fjets_poscsv_;
  mutable bool c_fjets_poscsv_;
  std::vector<float>  fjets_pt_;
  std::vector<float>  *p_fjets_pt_;
  TBranch *b_fjets_pt_;
  mutable bool c_fjets_pt_;
  std::vector<float>  fjets_sumcsv_;
  std::vector<float>  *p_fjets_sumcsv_;
  TBranch *b_fjets_sumcsv_;
  mutable bool c_fjets_sumcsv_;
  std::vector<float>  jets_csv_;
  std::vector<float>  *p_jets_csv_;
  TBranch *b_jets_csv_;
  mutable bool c_jets_csv_;
  std::vector<float>  jets_eta_;
  std::vector<float>  *p_jets_eta_;
  TBranch *b_jets_eta_;
  mutable bool c_jets_eta_;
  std::vector<float>  jets_m_;
  std::vector<float>  *p_jets_m_;
  TBranch *b_jets_m_;
  mutable bool c_jets_m_;
  std::vector<float>  jets_phi_;
  std::vector<float>  *p_jets_phi_;
  TBranch *b_jets_phi_;
  mutable bool c_jets_phi_;
  std::vector<float>  jets_pt_;
  std::vector<float>  *p_jets_pt_;
  TBranch *b_jets_pt_;
  mutable bool c_jets_pt_;
  std::vector<float>  mus_d0_;
  std::vector<float>  *p_mus_d0_;
  TBranch *b_mus_d0_;
  mutable bool c_mus_d0_;
  std::vector<float>  mus_dz_;
  std::vector<float>  *p_mus_dz_;
  TBranch *b_mus_dz_;
  mutable bool c_mus_dz_;
  std::vector<float>  mus_eta_;
  std::vector<float>  *p_mus_eta_;
  TBranch *b_mus_eta_;
  mutable bool c_mus_eta_;
  std::vector<float>  mus_phi_;
  std::vector<float>  *p_mus_phi_;
  TBranch *b_mus_phi_;
  mutable bool c_mus_phi_;
  std::vector<float>  mus_pt_;
  std::vector<float>  *p_mus_pt_;
  TBranch *b_mus_pt_;
  mutable bool c_mus_pt_;
  std::vector<int>  els_charge_;
  std::vector<int>  *p_els_charge_;
  TBranch *b_els_charge_;
  mutable bool c_els_charge_;
  std::vector<int>  fjets08_btags_;
  std::vector<int>  *p_fjets08_btags_;
  TBranch *b_fjets08_btags_;
  mutable bool c_fjets08_btags_;
  std::vector<int>  fjets08_nconst_;
  std::vector<int>  *p_fjets08_nconst_;
  TBranch *b_fjets08_nconst_;
  mutable bool c_fjets08_nconst_;
  std::vector<int>  fjets_btags_;
  std::vector<int>  *p_fjets_btags_;
  TBranch *b_fjets_btags_;
  mutable bool c_fjets_btags_;
  std::vector<int>  fjets_nconst_;
  std::vector<int>  *p_fjets_nconst_;
  TBranch *b_fjets_nconst_;
  mutable bool c_fjets_nconst_;
  std::vector<int>  jets_fjet08_index_;
  std::vector<int>  *p_jets_fjet08_index_;
  TBranch *b_jets_fjet08_index_;
  mutable bool c_jets_fjet08_index_;
  std::vector<int>  jets_fjet_index_;
  std::vector<int>  *p_jets_fjet_index_;
  TBranch *b_jets_fjet_index_;
  mutable bool c_jets_fjet_index_;
  std::vector<int>  mus_charge_;
  std::vector<int>  *p_mus_charge_;
  TBranch *b_mus_charge_;
  mutable bool c_mus_charge_;
};

small_tree* NewTree(const std::type_info &type);

#include "small_tree_full.hpp"
#include "small_tree_quick.hpp"
#include "small_tree_rpv.hpp"

#endif
