// small_tree_full: full version of small_tree to handle reduce tree ntuples
// File generated with generate_small_tree.exe

#ifndef H_SMALL_TREE_FULL
#define H_SMALL_TREE_FULL

#include <vector>
#include <string>

#include "TTree.h"
#include "TChain.h"

#include "small_tree.hpp"

class small_tree_full : public small_tree{
public:
  small_tree_full(); // Constructor to create tree
  small_tree_full(const std::string &filename); // Constructor to read tree

  virtual void GetEntry(const long entry);

  virtual void Fill();

  virtual std::string Type() const;

  virtual ~small_tree_full();

  virtual float  const & dphi_neutralinos() const;
  virtual float  & dphi_neutralinos();
  virtual float  const & dphi_wlep() const;
  virtual float  & dphi_wlep();
  virtual float  const & dphi_wlep_reliso() const;
  virtual float  & dphi_wlep_reliso();
  virtual float  const & gen_ht() const;
  virtual float  & gen_ht();
  virtual float  const & gen_met() const;
  virtual float  & gen_met();
  virtual float  const & gen_met_phi() const;
  virtual float  & gen_met_phi();
  virtual float  const & gen_mj() const;
  virtual float  & gen_mj();
  virtual float  const & ht40() const;
  virtual float  & ht40();
  virtual float  const & ht_isr() const;
  virtual float  & ht_isr();
  virtual float  const & ht_isr_me() const;
  virtual float  & ht_isr_me();
  virtual float  const & ht_isr_nonme() const;
  virtual float  & ht_isr_nonme();
  virtual float  const & ht_isr_tru() const;
  virtual float  & ht_isr_tru();
  virtual float  const & ht_nonb() const;
  virtual float  & ht_nonb();
  virtual float  const & ht_sub() const;
  virtual float  & ht_sub();
  virtual float  const & lep_eta() const;
  virtual float  & lep_eta();
  virtual float  const & lep_eta_reliso() const;
  virtual float  & lep_eta_reliso();
  virtual float  const & lep_phi() const;
  virtual float  & lep_phi();
  virtual float  const & lep_phi_reliso() const;
  virtual float  & lep_phi_reliso();
  virtual float  const & lep_pt() const;
  virtual float  & lep_pt();
  virtual float  const & lep_pt_reliso() const;
  virtual float  & lep_pt_reliso();
  virtual float  const & max_dphi_bb() const;
  virtual float  & max_dphi_bb();
  virtual float  const & max_dphi_blep() const;
  virtual float  & max_dphi_blep();
  virtual float  const & max_dphi_bmet() const;
  virtual float  & max_dphi_bmet();
  virtual float  const & max_dr_bb() const;
  virtual float  & max_dr_bb();
  virtual float  const & max_dr_blep() const;
  virtual float  & max_dr_blep();
  virtual float  const & max_m_bb() const;
  virtual float  & max_m_bb();
  virtual float  const & max_m_blep() const;
  virtual float  & max_m_blep();
  virtual float  const & max_mt_bmet() const;
  virtual float  & max_mt_bmet();
  virtual float  const & max_pt_bb() const;
  virtual float  & max_pt_bb();
  virtual float  const & max_pt_blep() const;
  virtual float  & max_pt_blep();
  virtual float  const & max_pt_bmet() const;
  virtual float  & max_pt_bmet();
  virtual float  const & mht_sub() const;
  virtual float  & mht_sub();
  virtual float  const & min_dphi_bb() const;
  virtual float  & min_dphi_bb();
  virtual float  const & min_dphi_blep() const;
  virtual float  & min_dphi_blep();
  virtual float  const & min_dphi_bmet() const;
  virtual float  & min_dphi_bmet();
  virtual float  const & min_dr_bb() const;
  virtual float  & min_dr_bb();
  virtual float  const & min_dr_blep() const;
  virtual float  & min_dr_blep();
  virtual float  const & min_m_bb() const;
  virtual float  & min_m_bb();
  virtual float  const & min_m_blep() const;
  virtual float  & min_m_blep();
  virtual float  const & min_mt_bmet() const;
  virtual float  & min_mt_bmet();
  virtual float  const & min_mt_bmet_with_w_mass() const;
  virtual float  & min_mt_bmet_with_w_mass();
  virtual float  const & min_pt_bb() const;
  virtual float  & min_pt_bb();
  virtual float  const & min_pt_blep() const;
  virtual float  & min_pt_blep();
  virtual float  const & min_pt_bmet() const;
  virtual float  & min_pt_bmet();
  virtual float  const & mindphin_metjet() const;
  virtual float  & mindphin_metjet();
  virtual float  const & mj15() const;
  virtual float  & mj15();
  virtual float  const & mj_sub() const;
  virtual float  & mj_sub();
  virtual float  const & mt_reliso() const;
  virtual float  & mt_reliso();
  virtual float  const & st() const;
  virtual float  & st();
  virtual float  const & st_reliso() const;
  virtual float  & st_reliso();
  virtual float  const & tru_gluglu_dphi() const;
  virtual float  & tru_gluglu_dphi();
  virtual float  const & tru_gluglu_m() const;
  virtual float  & tru_gluglu_m();
  virtual float  const & tru_gluglu_pt() const;
  virtual float  & tru_gluglu_pt();
  virtual float  const & tru_gluglu_ptdiff() const;
  virtual float  & tru_gluglu_ptdiff();
  virtual float  const & tru_sphericity() const;
  virtual float  & tru_sphericity();
  virtual float  const & tru_tt_dphi() const;
  virtual float  & tru_tt_dphi();
  virtual float  const & tru_tt_m() const;
  virtual float  & tru_tt_m();
  virtual float  const & tru_tt_pt() const;
  virtual float  & tru_tt_pt();
  virtual float  const & tru_tt_ptdiff() const;
  virtual float  & tru_tt_ptdiff();
  virtual float  const & trutop1_phi() const;
  virtual float  & trutop1_phi();
  virtual float  const & trutop1_pt() const;
  virtual float  & trutop1_pt();
  virtual float  const & trutop2_phi() const;
  virtual float  & trutop2_phi();
  virtual float  const & trutop2_pt() const;
  virtual float  & trutop2_pt();
  virtual int  const & lep_charge() const;
  virtual int  & lep_charge();
  virtual int  const & lep_charge_reliso() const;
  virtual int  & lep_charge_reliso();
  virtual int  const & n_isr_me() const;
  virtual int  & n_isr_me();
  virtual int  const & n_isr_nonme() const;
  virtual int  & n_isr_nonme();
  virtual int  const & nbadjets() const;
  virtual int  & nbadjets();
  virtual int  const & nbl40() const;
  virtual int  & nbl40();
  virtual int  const & nbl_sub() const;
  virtual int  & nbl_sub();
  virtual int  const & nbm40() const;
  virtual int  & nbm40();
  virtual int  const & nbm_sub() const;
  virtual int  & nbm_sub();
  virtual int  const & nbt40() const;
  virtual int  & nbt40();
  virtual int  const & nbt_sub() const;
  virtual int  & nbt_sub();
  virtual int  const & nels_reliso() const;
  virtual int  & nels_reliso();
  virtual int  const & nfjets15() const;
  virtual int  & nfjets15();
  virtual int  const & nfsubjets() const;
  virtual int  & nfsubjets();
  virtual int  const & ngenfjets() const;
  virtual int  & ngenfjets();
  virtual int  const & ngenjets() const;
  virtual int  & ngenjets();
  virtual int  const & njets40() const;
  virtual int  & njets40();
  virtual int  const & nleps_reliso() const;
  virtual int  & nleps_reliso();
  virtual int  const & nmus_reliso() const;
  virtual int  & nmus_reliso();
  virtual int  const & nsubjets() const;
  virtual int  & nsubjets();
  virtual int  const & ntks() const;
  virtual int  & ntks();
  virtual int  const & ntks_chg() const;
  virtual int  & ntks_chg();
  virtual int  const & ntks_chg_reliso() const;
  virtual int  & ntks_chg_reliso();
  virtual int  const & nvels_reliso() const;
  virtual int  & nvels_reliso();
  virtual int  const & nvmus_reliso() const;
  virtual int  & nvmus_reliso();
  virtual std::vector<bool>  const & badjets_islep() const;
  virtual std::vector<bool>  & badjets_islep();
  virtual std::vector<bool>  const & els_tru_tm() const;
  virtual std::vector<bool>  & els_tru_tm();
  virtual std::vector<bool>  const & mus_tru_tm() const;
  virtual std::vector<bool>  & mus_tru_tm();
  virtual std::vector<bool>  const & tks_from_tau() const;
  virtual std::vector<bool>  & tks_from_tau();
  virtual std::vector<bool>  const & tks_from_tauhad() const;
  virtual std::vector<bool>  & tks_from_tauhad();
  virtual std::vector<bool>  const & tks_from_taulep() const;
  virtual std::vector<bool>  & tks_from_taulep();
  virtual std::vector<bool>  const & tks_from_w() const;
  virtual std::vector<bool>  & tks_from_w();
  virtual std::vector<bool>  const & tks_is_primary() const;
  virtual std::vector<bool>  & tks_is_primary();
  virtual std::vector<bool>  const & tks_is_primary_reliso() const;
  virtual std::vector<bool>  & tks_is_primary_reliso();
  virtual std::vector<bool>  const & tks_is_sig_lep() const;
  virtual std::vector<bool>  & tks_is_sig_lep();
  virtual std::vector<float>  const & badjets_eta() const;
  virtual std::vector<float>  & badjets_eta();
  virtual std::vector<float>  const & badjets_id() const;
  virtual std::vector<float>  & badjets_id();
  virtual std::vector<float>  const & badjets_m() const;
  virtual std::vector<float>  & badjets_m();
  virtual std::vector<float>  const & badjets_phi() const;
  virtual std::vector<float>  & badjets_phi();
  virtual std::vector<float>  const & badjets_pt() const;
  virtual std::vector<float>  & badjets_pt();
  virtual std::vector<float>  const & els_miniso_10() const;
  virtual std::vector<float>  & els_miniso_10();
  virtual std::vector<float>  const & els_miniso_10_ch() const;
  virtual std::vector<float>  & els_miniso_10_ch();
  virtual std::vector<float>  const & els_miniso_tr10() const;
  virtual std::vector<float>  & els_miniso_tr10();
  virtual std::vector<float>  const & els_miniso_tr10_ch() const;
  virtual std::vector<float>  & els_miniso_tr10_ch();
  virtual std::vector<float>  const & els_mt() const;
  virtual std::vector<float>  & els_mt();
  virtual std::vector<float>  const & els_reliso() const;
  virtual std::vector<float>  & els_reliso();
  virtual std::vector<float>  const & els_reliso_r01() const;
  virtual std::vector<float>  & els_reliso_r01();
  virtual std::vector<float>  const & els_reliso_r015() const;
  virtual std::vector<float>  & els_reliso_r015();
  virtual std::vector<float>  const & els_reliso_r02() const;
  virtual std::vector<float>  & els_reliso_r02();
  virtual std::vector<float>  const & els_reliso_r03() const;
  virtual std::vector<float>  & els_reliso_r03();
  virtual std::vector<float>  const & els_reliso_r04() const;
  virtual std::vector<float>  & els_reliso_r04();
  virtual std::vector<float>  const & els_tru_dr() const;
  virtual std::vector<float>  & els_tru_dr();
  virtual std::vector<float>  const & fjets15_eta() const;
  virtual std::vector<float>  & fjets15_eta();
  virtual std::vector<float>  const & fjets15_m() const;
  virtual std::vector<float>  & fjets15_m();
  virtual std::vector<float>  const & fjets15_phi() const;
  virtual std::vector<float>  & fjets15_phi();
  virtual std::vector<float>  const & fjets15_poscsv() const;
  virtual std::vector<float>  & fjets15_poscsv();
  virtual std::vector<float>  const & fjets15_pt() const;
  virtual std::vector<float>  & fjets15_pt();
  virtual std::vector<float>  const & fjets15_sumcsv() const;
  virtual std::vector<float>  & fjets15_sumcsv();
  virtual std::vector<float>  const & fsubjets_eta() const;
  virtual std::vector<float>  & fsubjets_eta();
  virtual std::vector<float>  const & fsubjets_m() const;
  virtual std::vector<float>  & fsubjets_m();
  virtual std::vector<float>  const & fsubjets_phi() const;
  virtual std::vector<float>  & fsubjets_phi();
  virtual std::vector<float>  const & fsubjets_poscsv() const;
  virtual std::vector<float>  & fsubjets_poscsv();
  virtual std::vector<float>  const & fsubjets_pt() const;
  virtual std::vector<float>  & fsubjets_pt();
  virtual std::vector<float>  const & fsubjets_sumcsv() const;
  virtual std::vector<float>  & fsubjets_sumcsv();
  virtual std::vector<float>  const & genfjets_eta() const;
  virtual std::vector<float>  & genfjets_eta();
  virtual std::vector<float>  const & genfjets_m() const;
  virtual std::vector<float>  & genfjets_m();
  virtual std::vector<float>  const & genfjets_phi() const;
  virtual std::vector<float>  & genfjets_phi();
  virtual std::vector<float>  const & genfjets_pt() const;
  virtual std::vector<float>  & genfjets_pt();
  virtual std::vector<float>  const & genjets_eta() const;
  virtual std::vector<float>  & genjets_eta();
  virtual std::vector<float>  const & genjets_m() const;
  virtual std::vector<float>  & genjets_m();
  virtual std::vector<float>  const & genjets_phi() const;
  virtual std::vector<float>  & genjets_phi();
  virtual std::vector<float>  const & genjets_pt() const;
  virtual std::vector<float>  & genjets_pt();
  virtual std::vector<float>  const & glu_proj_frac() const;
  virtual std::vector<float>  & glu_proj_frac();
  virtual std::vector<float>  const & jets_gen_pt() const;
  virtual std::vector<float>  & jets_gen_pt();
  virtual std::vector<float>  const & jets_id() const;
  virtual std::vector<float>  & jets_id();
  virtual std::vector<float>  const & jets_parton_pt() const;
  virtual std::vector<float>  & jets_parton_pt();
  virtual std::vector<float>  const & jets_pt_from_mini() const;
  virtual std::vector<float>  & jets_pt_from_mini();
  virtual std::vector<float>  const & mc_eta() const;
  virtual std::vector<float>  & mc_eta();
  virtual std::vector<float>  const & mc_phi() const;
  virtual std::vector<float>  & mc_phi();
  virtual std::vector<float>  const & mc_pt() const;
  virtual std::vector<float>  & mc_pt();
  virtual std::vector<float>  const & mus_miniso_10() const;
  virtual std::vector<float>  & mus_miniso_10();
  virtual std::vector<float>  const & mus_miniso_10_ch() const;
  virtual std::vector<float>  & mus_miniso_10_ch();
  virtual std::vector<float>  const & mus_miniso_tr10() const;
  virtual std::vector<float>  & mus_miniso_tr10();
  virtual std::vector<float>  const & mus_miniso_tr10_ch() const;
  virtual std::vector<float>  & mus_miniso_tr10_ch();
  virtual std::vector<float>  const & mus_mt() const;
  virtual std::vector<float>  & mus_mt();
  virtual std::vector<float>  const & mus_reliso() const;
  virtual std::vector<float>  & mus_reliso();
  virtual std::vector<float>  const & mus_reliso_r01() const;
  virtual std::vector<float>  & mus_reliso_r01();
  virtual std::vector<float>  const & mus_reliso_r015() const;
  virtual std::vector<float>  & mus_reliso_r015();
  virtual std::vector<float>  const & mus_reliso_r02() const;
  virtual std::vector<float>  & mus_reliso_r02();
  virtual std::vector<float>  const & mus_reliso_r03() const;
  virtual std::vector<float>  & mus_reliso_r03();
  virtual std::vector<float>  const & mus_reliso_r04() const;
  virtual std::vector<float>  & mus_reliso_r04();
  virtual std::vector<float>  const & mus_tru_dr() const;
  virtual std::vector<float>  & mus_tru_dr();
  virtual std::vector<float>  const & subjets_csv() const;
  virtual std::vector<float>  & subjets_csv();
  virtual std::vector<float>  const & subjets_eta() const;
  virtual std::vector<float>  & subjets_eta();
  virtual std::vector<float>  const & subjets_id() const;
  virtual std::vector<float>  & subjets_id();
  virtual std::vector<float>  const & subjets_m() const;
  virtual std::vector<float>  & subjets_m();
  virtual std::vector<float>  const & subjets_mindr() const;
  virtual std::vector<float>  & subjets_mindr();
  virtual std::vector<float>  const & subjets_phi() const;
  virtual std::vector<float>  & subjets_phi();
  virtual std::vector<float>  const & subjets_pt() const;
  virtual std::vector<float>  & subjets_pt();
  virtual std::vector<float>  const & subjets_subeta() const;
  virtual std::vector<float>  & subjets_subeta();
  virtual std::vector<float>  const & subjets_subm() const;
  virtual std::vector<float>  & subjets_subm();
  virtual std::vector<float>  const & subjets_subphi() const;
  virtual std::vector<float>  & subjets_subphi();
  virtual std::vector<float>  const & subjets_subpt() const;
  virtual std::vector<float>  & subjets_subpt();
  virtual std::vector<float>  const & tks_eta() const;
  virtual std::vector<float>  & tks_eta();
  virtual std::vector<float>  const & tks_mini_ch() const;
  virtual std::vector<float>  & tks_mini_ch();
  virtual std::vector<float>  const & tks_mini_ne() const;
  virtual std::vector<float>  & tks_mini_ne();
  virtual std::vector<float>  const & tks_mt() const;
  virtual std::vector<float>  & tks_mt();
  virtual std::vector<float>  const & tks_phi() const;
  virtual std::vector<float>  & tks_phi();
  virtual std::vector<float>  const & tks_pt() const;
  virtual std::vector<float>  & tks_pt();
  virtual std::vector<float>  const & tks_r02_ch() const;
  virtual std::vector<float>  & tks_r02_ch();
  virtual std::vector<float>  const & tks_r02_ne() const;
  virtual std::vector<float>  & tks_r02_ne();
  virtual std::vector<float>  const & tks_r03_ch() const;
  virtual std::vector<float>  & tks_r03_ch();
  virtual std::vector<float>  const & tks_r03_ne() const;
  virtual std::vector<float>  & tks_r03_ne();
  virtual std::vector<float>  const & tks_r04_ch() const;
  virtual std::vector<float>  & tks_r04_ch();
  virtual std::vector<float>  const & tks_r04_ne() const;
  virtual std::vector<float>  & tks_r04_ne();
  virtual std::vector<float>  const & tks_r05_ch() const;
  virtual std::vector<float>  & tks_r05_ch();
  virtual std::vector<float>  const & tks_r05_ne() const;
  virtual std::vector<float>  & tks_r05_ne();
  virtual std::vector<float>  const & tks_tru_dp() const;
  virtual std::vector<float>  & tks_tru_dp();
  virtual std::vector<float>  const & tks_tru_dr() const;
  virtual std::vector<float>  & tks_tru_dr();
  virtual std::vector<int>  const & els_tru_id() const;
  virtual std::vector<int>  & els_tru_id();
  virtual std::vector<int>  const & els_tru_momid() const;
  virtual std::vector<int>  & els_tru_momid();
  virtual std::vector<int>  const & fjets15_btags() const;
  virtual std::vector<int>  & fjets15_btags();
  virtual std::vector<int>  const & fjets15_nconst() const;
  virtual std::vector<int>  & fjets15_nconst();
  virtual std::vector<int>  const & fsubjets_btags() const;
  virtual std::vector<int>  & fsubjets_btags();
  virtual std::vector<int>  const & fsubjets_nconst() const;
  virtual std::vector<int>  & fsubjets_nconst();
  virtual std::vector<int>  const & genfjets_nconst() const;
  virtual std::vector<int>  & genfjets_nconst();
  virtual std::vector<int>  const & genjets_genfjet_index() const;
  virtual std::vector<int>  & genjets_genfjet_index();
  virtual std::vector<int>  const & genjets_isr_code() const;
  virtual std::vector<int>  & genjets_isr_code();
  virtual std::vector<int>  const & jets_fjet15_index() const;
  virtual std::vector<int>  & jets_fjet15_index();
  virtual std::vector<int>  const & jets_isr_code() const;
  virtual std::vector<int>  & jets_isr_code();
  virtual std::vector<int>  const & mc_id() const;
  virtual std::vector<int>  & mc_id();
  virtual std::vector<int>  const & mc_status() const;
  virtual std::vector<int>  & mc_status();
  virtual std::vector<int>  const & mus_tru_id() const;
  virtual std::vector<int>  & mus_tru_id();
  virtual std::vector<int>  const & mus_tru_momid() const;
  virtual std::vector<int>  & mus_tru_momid();
  virtual std::vector<int>  const & subjets_fsubjet_index() const;
  virtual std::vector<int>  & subjets_fsubjet_index();
  virtual std::vector<int>  const & subjets_nsub() const;
  virtual std::vector<int>  & subjets_nsub();
  virtual std::vector<int>  const & tks_charge() const;
  virtual std::vector<int>  & tks_charge();
  virtual std::vector<int>  const & tks_from_pv() const;
  virtual std::vector<int>  & tks_from_pv();
  virtual std::vector<int>  const & tks_id() const;
  virtual std::vector<int>  & tks_id();
  virtual std::vector<int>  const & tks_num_prongs() const;
  virtual std::vector<int>  & tks_num_prongs();
  virtual std::vector<int>  const & tks_tru_id() const;
  virtual std::vector<int>  & tks_tru_id();
  virtual std::vector<size_t>  const & mc_mom() const;
  virtual std::vector<size_t>  & mc_mom();
  virtual unsigned  const & mc_type() const;
  virtual unsigned  & mc_type();

private:
  float  dphi_neutralinos_;
  TBranch *b_dphi_neutralinos_;
  mutable bool c_dphi_neutralinos_;
  float  dphi_wlep_;
  TBranch *b_dphi_wlep_;
  mutable bool c_dphi_wlep_;
  float  dphi_wlep_reliso_;
  TBranch *b_dphi_wlep_reliso_;
  mutable bool c_dphi_wlep_reliso_;
  float  gen_ht_;
  TBranch *b_gen_ht_;
  mutable bool c_gen_ht_;
  float  gen_met_;
  TBranch *b_gen_met_;
  mutable bool c_gen_met_;
  float  gen_met_phi_;
  TBranch *b_gen_met_phi_;
  mutable bool c_gen_met_phi_;
  float  gen_mj_;
  TBranch *b_gen_mj_;
  mutable bool c_gen_mj_;
  float  ht40_;
  TBranch *b_ht40_;
  mutable bool c_ht40_;
  float  ht_isr_;
  TBranch *b_ht_isr_;
  mutable bool c_ht_isr_;
  float  ht_isr_me_;
  TBranch *b_ht_isr_me_;
  mutable bool c_ht_isr_me_;
  float  ht_isr_nonme_;
  TBranch *b_ht_isr_nonme_;
  mutable bool c_ht_isr_nonme_;
  float  ht_isr_tru_;
  TBranch *b_ht_isr_tru_;
  mutable bool c_ht_isr_tru_;
  float  ht_nonb_;
  TBranch *b_ht_nonb_;
  mutable bool c_ht_nonb_;
  float  ht_sub_;
  TBranch *b_ht_sub_;
  mutable bool c_ht_sub_;
  float  lep_eta_;
  TBranch *b_lep_eta_;
  mutable bool c_lep_eta_;
  float  lep_eta_reliso_;
  TBranch *b_lep_eta_reliso_;
  mutable bool c_lep_eta_reliso_;
  float  lep_phi_;
  TBranch *b_lep_phi_;
  mutable bool c_lep_phi_;
  float  lep_phi_reliso_;
  TBranch *b_lep_phi_reliso_;
  mutable bool c_lep_phi_reliso_;
  float  lep_pt_;
  TBranch *b_lep_pt_;
  mutable bool c_lep_pt_;
  float  lep_pt_reliso_;
  TBranch *b_lep_pt_reliso_;
  mutable bool c_lep_pt_reliso_;
  float  max_dphi_bb_;
  TBranch *b_max_dphi_bb_;
  mutable bool c_max_dphi_bb_;
  float  max_dphi_blep_;
  TBranch *b_max_dphi_blep_;
  mutable bool c_max_dphi_blep_;
  float  max_dphi_bmet_;
  TBranch *b_max_dphi_bmet_;
  mutable bool c_max_dphi_bmet_;
  float  max_dr_bb_;
  TBranch *b_max_dr_bb_;
  mutable bool c_max_dr_bb_;
  float  max_dr_blep_;
  TBranch *b_max_dr_blep_;
  mutable bool c_max_dr_blep_;
  float  max_m_bb_;
  TBranch *b_max_m_bb_;
  mutable bool c_max_m_bb_;
  float  max_m_blep_;
  TBranch *b_max_m_blep_;
  mutable bool c_max_m_blep_;
  float  max_mt_bmet_;
  TBranch *b_max_mt_bmet_;
  mutable bool c_max_mt_bmet_;
  float  max_pt_bb_;
  TBranch *b_max_pt_bb_;
  mutable bool c_max_pt_bb_;
  float  max_pt_blep_;
  TBranch *b_max_pt_blep_;
  mutable bool c_max_pt_blep_;
  float  max_pt_bmet_;
  TBranch *b_max_pt_bmet_;
  mutable bool c_max_pt_bmet_;
  float  mht_sub_;
  TBranch *b_mht_sub_;
  mutable bool c_mht_sub_;
  float  min_dphi_bb_;
  TBranch *b_min_dphi_bb_;
  mutable bool c_min_dphi_bb_;
  float  min_dphi_blep_;
  TBranch *b_min_dphi_blep_;
  mutable bool c_min_dphi_blep_;
  float  min_dphi_bmet_;
  TBranch *b_min_dphi_bmet_;
  mutable bool c_min_dphi_bmet_;
  float  min_dr_bb_;
  TBranch *b_min_dr_bb_;
  mutable bool c_min_dr_bb_;
  float  min_dr_blep_;
  TBranch *b_min_dr_blep_;
  mutable bool c_min_dr_blep_;
  float  min_m_bb_;
  TBranch *b_min_m_bb_;
  mutable bool c_min_m_bb_;
  float  min_m_blep_;
  TBranch *b_min_m_blep_;
  mutable bool c_min_m_blep_;
  float  min_mt_bmet_;
  TBranch *b_min_mt_bmet_;
  mutable bool c_min_mt_bmet_;
  float  min_mt_bmet_with_w_mass_;
  TBranch *b_min_mt_bmet_with_w_mass_;
  mutable bool c_min_mt_bmet_with_w_mass_;
  float  min_pt_bb_;
  TBranch *b_min_pt_bb_;
  mutable bool c_min_pt_bb_;
  float  min_pt_blep_;
  TBranch *b_min_pt_blep_;
  mutable bool c_min_pt_blep_;
  float  min_pt_bmet_;
  TBranch *b_min_pt_bmet_;
  mutable bool c_min_pt_bmet_;
  float  mindphin_metjet_;
  TBranch *b_mindphin_metjet_;
  mutable bool c_mindphin_metjet_;
  float  mj15_;
  TBranch *b_mj15_;
  mutable bool c_mj15_;
  float  mj_sub_;
  TBranch *b_mj_sub_;
  mutable bool c_mj_sub_;
  float  mt_reliso_;
  TBranch *b_mt_reliso_;
  mutable bool c_mt_reliso_;
  float  st_;
  TBranch *b_st_;
  mutable bool c_st_;
  float  st_reliso_;
  TBranch *b_st_reliso_;
  mutable bool c_st_reliso_;
  float  tru_gluglu_dphi_;
  TBranch *b_tru_gluglu_dphi_;
  mutable bool c_tru_gluglu_dphi_;
  float  tru_gluglu_m_;
  TBranch *b_tru_gluglu_m_;
  mutable bool c_tru_gluglu_m_;
  float  tru_gluglu_pt_;
  TBranch *b_tru_gluglu_pt_;
  mutable bool c_tru_gluglu_pt_;
  float  tru_gluglu_ptdiff_;
  TBranch *b_tru_gluglu_ptdiff_;
  mutable bool c_tru_gluglu_ptdiff_;
  float  tru_sphericity_;
  TBranch *b_tru_sphericity_;
  mutable bool c_tru_sphericity_;
  float  tru_tt_dphi_;
  TBranch *b_tru_tt_dphi_;
  mutable bool c_tru_tt_dphi_;
  float  tru_tt_m_;
  TBranch *b_tru_tt_m_;
  mutable bool c_tru_tt_m_;
  float  tru_tt_pt_;
  TBranch *b_tru_tt_pt_;
  mutable bool c_tru_tt_pt_;
  float  tru_tt_ptdiff_;
  TBranch *b_tru_tt_ptdiff_;
  mutable bool c_tru_tt_ptdiff_;
  float  trutop1_phi_;
  TBranch *b_trutop1_phi_;
  mutable bool c_trutop1_phi_;
  float  trutop1_pt_;
  TBranch *b_trutop1_pt_;
  mutable bool c_trutop1_pt_;
  float  trutop2_phi_;
  TBranch *b_trutop2_phi_;
  mutable bool c_trutop2_phi_;
  float  trutop2_pt_;
  TBranch *b_trutop2_pt_;
  mutable bool c_trutop2_pt_;
  int  lep_charge_;
  TBranch *b_lep_charge_;
  mutable bool c_lep_charge_;
  int  lep_charge_reliso_;
  TBranch *b_lep_charge_reliso_;
  mutable bool c_lep_charge_reliso_;
  int  n_isr_me_;
  TBranch *b_n_isr_me_;
  mutable bool c_n_isr_me_;
  int  n_isr_nonme_;
  TBranch *b_n_isr_nonme_;
  mutable bool c_n_isr_nonme_;
  int  nbadjets_;
  TBranch *b_nbadjets_;
  mutable bool c_nbadjets_;
  int  nbl40_;
  TBranch *b_nbl40_;
  mutable bool c_nbl40_;
  int  nbl_sub_;
  TBranch *b_nbl_sub_;
  mutable bool c_nbl_sub_;
  int  nbm40_;
  TBranch *b_nbm40_;
  mutable bool c_nbm40_;
  int  nbm_sub_;
  TBranch *b_nbm_sub_;
  mutable bool c_nbm_sub_;
  int  nbt40_;
  TBranch *b_nbt40_;
  mutable bool c_nbt40_;
  int  nbt_sub_;
  TBranch *b_nbt_sub_;
  mutable bool c_nbt_sub_;
  int  nels_reliso_;
  TBranch *b_nels_reliso_;
  mutable bool c_nels_reliso_;
  int  nfjets15_;
  TBranch *b_nfjets15_;
  mutable bool c_nfjets15_;
  int  nfsubjets_;
  TBranch *b_nfsubjets_;
  mutable bool c_nfsubjets_;
  int  ngenfjets_;
  TBranch *b_ngenfjets_;
  mutable bool c_ngenfjets_;
  int  ngenjets_;
  TBranch *b_ngenjets_;
  mutable bool c_ngenjets_;
  int  njets40_;
  TBranch *b_njets40_;
  mutable bool c_njets40_;
  int  nleps_reliso_;
  TBranch *b_nleps_reliso_;
  mutable bool c_nleps_reliso_;
  int  nmus_reliso_;
  TBranch *b_nmus_reliso_;
  mutable bool c_nmus_reliso_;
  int  nsubjets_;
  TBranch *b_nsubjets_;
  mutable bool c_nsubjets_;
  int  ntks_;
  TBranch *b_ntks_;
  mutable bool c_ntks_;
  int  ntks_chg_;
  TBranch *b_ntks_chg_;
  mutable bool c_ntks_chg_;
  int  ntks_chg_reliso_;
  TBranch *b_ntks_chg_reliso_;
  mutable bool c_ntks_chg_reliso_;
  int  nvels_reliso_;
  TBranch *b_nvels_reliso_;
  mutable bool c_nvels_reliso_;
  int  nvmus_reliso_;
  TBranch *b_nvmus_reliso_;
  mutable bool c_nvmus_reliso_;
  std::vector<bool>  badjets_islep_;
  std::vector<bool>  *p_badjets_islep_;
  TBranch *b_badjets_islep_;
  mutable bool c_badjets_islep_;
  std::vector<bool>  els_tru_tm_;
  std::vector<bool>  *p_els_tru_tm_;
  TBranch *b_els_tru_tm_;
  mutable bool c_els_tru_tm_;
  std::vector<bool>  mus_tru_tm_;
  std::vector<bool>  *p_mus_tru_tm_;
  TBranch *b_mus_tru_tm_;
  mutable bool c_mus_tru_tm_;
  std::vector<bool>  tks_from_tau_;
  std::vector<bool>  *p_tks_from_tau_;
  TBranch *b_tks_from_tau_;
  mutable bool c_tks_from_tau_;
  std::vector<bool>  tks_from_tauhad_;
  std::vector<bool>  *p_tks_from_tauhad_;
  TBranch *b_tks_from_tauhad_;
  mutable bool c_tks_from_tauhad_;
  std::vector<bool>  tks_from_taulep_;
  std::vector<bool>  *p_tks_from_taulep_;
  TBranch *b_tks_from_taulep_;
  mutable bool c_tks_from_taulep_;
  std::vector<bool>  tks_from_w_;
  std::vector<bool>  *p_tks_from_w_;
  TBranch *b_tks_from_w_;
  mutable bool c_tks_from_w_;
  std::vector<bool>  tks_is_primary_;
  std::vector<bool>  *p_tks_is_primary_;
  TBranch *b_tks_is_primary_;
  mutable bool c_tks_is_primary_;
  std::vector<bool>  tks_is_primary_reliso_;
  std::vector<bool>  *p_tks_is_primary_reliso_;
  TBranch *b_tks_is_primary_reliso_;
  mutable bool c_tks_is_primary_reliso_;
  std::vector<bool>  tks_is_sig_lep_;
  std::vector<bool>  *p_tks_is_sig_lep_;
  TBranch *b_tks_is_sig_lep_;
  mutable bool c_tks_is_sig_lep_;
  std::vector<float>  badjets_eta_;
  std::vector<float>  *p_badjets_eta_;
  TBranch *b_badjets_eta_;
  mutable bool c_badjets_eta_;
  std::vector<float>  badjets_id_;
  std::vector<float>  *p_badjets_id_;
  TBranch *b_badjets_id_;
  mutable bool c_badjets_id_;
  std::vector<float>  badjets_m_;
  std::vector<float>  *p_badjets_m_;
  TBranch *b_badjets_m_;
  mutable bool c_badjets_m_;
  std::vector<float>  badjets_phi_;
  std::vector<float>  *p_badjets_phi_;
  TBranch *b_badjets_phi_;
  mutable bool c_badjets_phi_;
  std::vector<float>  badjets_pt_;
  std::vector<float>  *p_badjets_pt_;
  TBranch *b_badjets_pt_;
  mutable bool c_badjets_pt_;
  std::vector<float>  els_miniso_10_;
  std::vector<float>  *p_els_miniso_10_;
  TBranch *b_els_miniso_10_;
  mutable bool c_els_miniso_10_;
  std::vector<float>  els_miniso_10_ch_;
  std::vector<float>  *p_els_miniso_10_ch_;
  TBranch *b_els_miniso_10_ch_;
  mutable bool c_els_miniso_10_ch_;
  std::vector<float>  els_miniso_tr10_;
  std::vector<float>  *p_els_miniso_tr10_;
  TBranch *b_els_miniso_tr10_;
  mutable bool c_els_miniso_tr10_;
  std::vector<float>  els_miniso_tr10_ch_;
  std::vector<float>  *p_els_miniso_tr10_ch_;
  TBranch *b_els_miniso_tr10_ch_;
  mutable bool c_els_miniso_tr10_ch_;
  std::vector<float>  els_mt_;
  std::vector<float>  *p_els_mt_;
  TBranch *b_els_mt_;
  mutable bool c_els_mt_;
  std::vector<float>  els_reliso_;
  std::vector<float>  *p_els_reliso_;
  TBranch *b_els_reliso_;
  mutable bool c_els_reliso_;
  std::vector<float>  els_reliso_r01_;
  std::vector<float>  *p_els_reliso_r01_;
  TBranch *b_els_reliso_r01_;
  mutable bool c_els_reliso_r01_;
  std::vector<float>  els_reliso_r015_;
  std::vector<float>  *p_els_reliso_r015_;
  TBranch *b_els_reliso_r015_;
  mutable bool c_els_reliso_r015_;
  std::vector<float>  els_reliso_r02_;
  std::vector<float>  *p_els_reliso_r02_;
  TBranch *b_els_reliso_r02_;
  mutable bool c_els_reliso_r02_;
  std::vector<float>  els_reliso_r03_;
  std::vector<float>  *p_els_reliso_r03_;
  TBranch *b_els_reliso_r03_;
  mutable bool c_els_reliso_r03_;
  std::vector<float>  els_reliso_r04_;
  std::vector<float>  *p_els_reliso_r04_;
  TBranch *b_els_reliso_r04_;
  mutable bool c_els_reliso_r04_;
  std::vector<float>  els_tru_dr_;
  std::vector<float>  *p_els_tru_dr_;
  TBranch *b_els_tru_dr_;
  mutable bool c_els_tru_dr_;
  std::vector<float>  fjets15_eta_;
  std::vector<float>  *p_fjets15_eta_;
  TBranch *b_fjets15_eta_;
  mutable bool c_fjets15_eta_;
  std::vector<float>  fjets15_m_;
  std::vector<float>  *p_fjets15_m_;
  TBranch *b_fjets15_m_;
  mutable bool c_fjets15_m_;
  std::vector<float>  fjets15_phi_;
  std::vector<float>  *p_fjets15_phi_;
  TBranch *b_fjets15_phi_;
  mutable bool c_fjets15_phi_;
  std::vector<float>  fjets15_poscsv_;
  std::vector<float>  *p_fjets15_poscsv_;
  TBranch *b_fjets15_poscsv_;
  mutable bool c_fjets15_poscsv_;
  std::vector<float>  fjets15_pt_;
  std::vector<float>  *p_fjets15_pt_;
  TBranch *b_fjets15_pt_;
  mutable bool c_fjets15_pt_;
  std::vector<float>  fjets15_sumcsv_;
  std::vector<float>  *p_fjets15_sumcsv_;
  TBranch *b_fjets15_sumcsv_;
  mutable bool c_fjets15_sumcsv_;
  std::vector<float>  fsubjets_eta_;
  std::vector<float>  *p_fsubjets_eta_;
  TBranch *b_fsubjets_eta_;
  mutable bool c_fsubjets_eta_;
  std::vector<float>  fsubjets_m_;
  std::vector<float>  *p_fsubjets_m_;
  TBranch *b_fsubjets_m_;
  mutable bool c_fsubjets_m_;
  std::vector<float>  fsubjets_phi_;
  std::vector<float>  *p_fsubjets_phi_;
  TBranch *b_fsubjets_phi_;
  mutable bool c_fsubjets_phi_;
  std::vector<float>  fsubjets_poscsv_;
  std::vector<float>  *p_fsubjets_poscsv_;
  TBranch *b_fsubjets_poscsv_;
  mutable bool c_fsubjets_poscsv_;
  std::vector<float>  fsubjets_pt_;
  std::vector<float>  *p_fsubjets_pt_;
  TBranch *b_fsubjets_pt_;
  mutable bool c_fsubjets_pt_;
  std::vector<float>  fsubjets_sumcsv_;
  std::vector<float>  *p_fsubjets_sumcsv_;
  TBranch *b_fsubjets_sumcsv_;
  mutable bool c_fsubjets_sumcsv_;
  std::vector<float>  genfjets_eta_;
  std::vector<float>  *p_genfjets_eta_;
  TBranch *b_genfjets_eta_;
  mutable bool c_genfjets_eta_;
  std::vector<float>  genfjets_m_;
  std::vector<float>  *p_genfjets_m_;
  TBranch *b_genfjets_m_;
  mutable bool c_genfjets_m_;
  std::vector<float>  genfjets_phi_;
  std::vector<float>  *p_genfjets_phi_;
  TBranch *b_genfjets_phi_;
  mutable bool c_genfjets_phi_;
  std::vector<float>  genfjets_pt_;
  std::vector<float>  *p_genfjets_pt_;
  TBranch *b_genfjets_pt_;
  mutable bool c_genfjets_pt_;
  std::vector<float>  genjets_eta_;
  std::vector<float>  *p_genjets_eta_;
  TBranch *b_genjets_eta_;
  mutable bool c_genjets_eta_;
  std::vector<float>  genjets_m_;
  std::vector<float>  *p_genjets_m_;
  TBranch *b_genjets_m_;
  mutable bool c_genjets_m_;
  std::vector<float>  genjets_phi_;
  std::vector<float>  *p_genjets_phi_;
  TBranch *b_genjets_phi_;
  mutable bool c_genjets_phi_;
  std::vector<float>  genjets_pt_;
  std::vector<float>  *p_genjets_pt_;
  TBranch *b_genjets_pt_;
  mutable bool c_genjets_pt_;
  std::vector<float>  glu_proj_frac_;
  std::vector<float>  *p_glu_proj_frac_;
  TBranch *b_glu_proj_frac_;
  mutable bool c_glu_proj_frac_;
  std::vector<float>  jets_gen_pt_;
  std::vector<float>  *p_jets_gen_pt_;
  TBranch *b_jets_gen_pt_;
  mutable bool c_jets_gen_pt_;
  std::vector<float>  jets_id_;
  std::vector<float>  *p_jets_id_;
  TBranch *b_jets_id_;
  mutable bool c_jets_id_;
  std::vector<float>  jets_parton_pt_;
  std::vector<float>  *p_jets_parton_pt_;
  TBranch *b_jets_parton_pt_;
  mutable bool c_jets_parton_pt_;
  std::vector<float>  jets_pt_from_mini_;
  std::vector<float>  *p_jets_pt_from_mini_;
  TBranch *b_jets_pt_from_mini_;
  mutable bool c_jets_pt_from_mini_;
  std::vector<float>  mc_eta_;
  std::vector<float>  *p_mc_eta_;
  TBranch *b_mc_eta_;
  mutable bool c_mc_eta_;
  std::vector<float>  mc_phi_;
  std::vector<float>  *p_mc_phi_;
  TBranch *b_mc_phi_;
  mutable bool c_mc_phi_;
  std::vector<float>  mc_pt_;
  std::vector<float>  *p_mc_pt_;
  TBranch *b_mc_pt_;
  mutable bool c_mc_pt_;
  std::vector<float>  mus_miniso_10_;
  std::vector<float>  *p_mus_miniso_10_;
  TBranch *b_mus_miniso_10_;
  mutable bool c_mus_miniso_10_;
  std::vector<float>  mus_miniso_10_ch_;
  std::vector<float>  *p_mus_miniso_10_ch_;
  TBranch *b_mus_miniso_10_ch_;
  mutable bool c_mus_miniso_10_ch_;
  std::vector<float>  mus_miniso_tr10_;
  std::vector<float>  *p_mus_miniso_tr10_;
  TBranch *b_mus_miniso_tr10_;
  mutable bool c_mus_miniso_tr10_;
  std::vector<float>  mus_miniso_tr10_ch_;
  std::vector<float>  *p_mus_miniso_tr10_ch_;
  TBranch *b_mus_miniso_tr10_ch_;
  mutable bool c_mus_miniso_tr10_ch_;
  std::vector<float>  mus_mt_;
  std::vector<float>  *p_mus_mt_;
  TBranch *b_mus_mt_;
  mutable bool c_mus_mt_;
  std::vector<float>  mus_reliso_;
  std::vector<float>  *p_mus_reliso_;
  TBranch *b_mus_reliso_;
  mutable bool c_mus_reliso_;
  std::vector<float>  mus_reliso_r01_;
  std::vector<float>  *p_mus_reliso_r01_;
  TBranch *b_mus_reliso_r01_;
  mutable bool c_mus_reliso_r01_;
  std::vector<float>  mus_reliso_r015_;
  std::vector<float>  *p_mus_reliso_r015_;
  TBranch *b_mus_reliso_r015_;
  mutable bool c_mus_reliso_r015_;
  std::vector<float>  mus_reliso_r02_;
  std::vector<float>  *p_mus_reliso_r02_;
  TBranch *b_mus_reliso_r02_;
  mutable bool c_mus_reliso_r02_;
  std::vector<float>  mus_reliso_r03_;
  std::vector<float>  *p_mus_reliso_r03_;
  TBranch *b_mus_reliso_r03_;
  mutable bool c_mus_reliso_r03_;
  std::vector<float>  mus_reliso_r04_;
  std::vector<float>  *p_mus_reliso_r04_;
  TBranch *b_mus_reliso_r04_;
  mutable bool c_mus_reliso_r04_;
  std::vector<float>  mus_tru_dr_;
  std::vector<float>  *p_mus_tru_dr_;
  TBranch *b_mus_tru_dr_;
  mutable bool c_mus_tru_dr_;
  std::vector<float>  subjets_csv_;
  std::vector<float>  *p_subjets_csv_;
  TBranch *b_subjets_csv_;
  mutable bool c_subjets_csv_;
  std::vector<float>  subjets_eta_;
  std::vector<float>  *p_subjets_eta_;
  TBranch *b_subjets_eta_;
  mutable bool c_subjets_eta_;
  std::vector<float>  subjets_id_;
  std::vector<float>  *p_subjets_id_;
  TBranch *b_subjets_id_;
  mutable bool c_subjets_id_;
  std::vector<float>  subjets_m_;
  std::vector<float>  *p_subjets_m_;
  TBranch *b_subjets_m_;
  mutable bool c_subjets_m_;
  std::vector<float>  subjets_mindr_;
  std::vector<float>  *p_subjets_mindr_;
  TBranch *b_subjets_mindr_;
  mutable bool c_subjets_mindr_;
  std::vector<float>  subjets_phi_;
  std::vector<float>  *p_subjets_phi_;
  TBranch *b_subjets_phi_;
  mutable bool c_subjets_phi_;
  std::vector<float>  subjets_pt_;
  std::vector<float>  *p_subjets_pt_;
  TBranch *b_subjets_pt_;
  mutable bool c_subjets_pt_;
  std::vector<float>  subjets_subeta_;
  std::vector<float>  *p_subjets_subeta_;
  TBranch *b_subjets_subeta_;
  mutable bool c_subjets_subeta_;
  std::vector<float>  subjets_subm_;
  std::vector<float>  *p_subjets_subm_;
  TBranch *b_subjets_subm_;
  mutable bool c_subjets_subm_;
  std::vector<float>  subjets_subphi_;
  std::vector<float>  *p_subjets_subphi_;
  TBranch *b_subjets_subphi_;
  mutable bool c_subjets_subphi_;
  std::vector<float>  subjets_subpt_;
  std::vector<float>  *p_subjets_subpt_;
  TBranch *b_subjets_subpt_;
  mutable bool c_subjets_subpt_;
  std::vector<float>  tks_eta_;
  std::vector<float>  *p_tks_eta_;
  TBranch *b_tks_eta_;
  mutable bool c_tks_eta_;
  std::vector<float>  tks_mini_ch_;
  std::vector<float>  *p_tks_mini_ch_;
  TBranch *b_tks_mini_ch_;
  mutable bool c_tks_mini_ch_;
  std::vector<float>  tks_mini_ne_;
  std::vector<float>  *p_tks_mini_ne_;
  TBranch *b_tks_mini_ne_;
  mutable bool c_tks_mini_ne_;
  std::vector<float>  tks_mt_;
  std::vector<float>  *p_tks_mt_;
  TBranch *b_tks_mt_;
  mutable bool c_tks_mt_;
  std::vector<float>  tks_phi_;
  std::vector<float>  *p_tks_phi_;
  TBranch *b_tks_phi_;
  mutable bool c_tks_phi_;
  std::vector<float>  tks_pt_;
  std::vector<float>  *p_tks_pt_;
  TBranch *b_tks_pt_;
  mutable bool c_tks_pt_;
  std::vector<float>  tks_r02_ch_;
  std::vector<float>  *p_tks_r02_ch_;
  TBranch *b_tks_r02_ch_;
  mutable bool c_tks_r02_ch_;
  std::vector<float>  tks_r02_ne_;
  std::vector<float>  *p_tks_r02_ne_;
  TBranch *b_tks_r02_ne_;
  mutable bool c_tks_r02_ne_;
  std::vector<float>  tks_r03_ch_;
  std::vector<float>  *p_tks_r03_ch_;
  TBranch *b_tks_r03_ch_;
  mutable bool c_tks_r03_ch_;
  std::vector<float>  tks_r03_ne_;
  std::vector<float>  *p_tks_r03_ne_;
  TBranch *b_tks_r03_ne_;
  mutable bool c_tks_r03_ne_;
  std::vector<float>  tks_r04_ch_;
  std::vector<float>  *p_tks_r04_ch_;
  TBranch *b_tks_r04_ch_;
  mutable bool c_tks_r04_ch_;
  std::vector<float>  tks_r04_ne_;
  std::vector<float>  *p_tks_r04_ne_;
  TBranch *b_tks_r04_ne_;
  mutable bool c_tks_r04_ne_;
  std::vector<float>  tks_r05_ch_;
  std::vector<float>  *p_tks_r05_ch_;
  TBranch *b_tks_r05_ch_;
  mutable bool c_tks_r05_ch_;
  std::vector<float>  tks_r05_ne_;
  std::vector<float>  *p_tks_r05_ne_;
  TBranch *b_tks_r05_ne_;
  mutable bool c_tks_r05_ne_;
  std::vector<float>  tks_tru_dp_;
  std::vector<float>  *p_tks_tru_dp_;
  TBranch *b_tks_tru_dp_;
  mutable bool c_tks_tru_dp_;
  std::vector<float>  tks_tru_dr_;
  std::vector<float>  *p_tks_tru_dr_;
  TBranch *b_tks_tru_dr_;
  mutable bool c_tks_tru_dr_;
  std::vector<int>  els_tru_id_;
  std::vector<int>  *p_els_tru_id_;
  TBranch *b_els_tru_id_;
  mutable bool c_els_tru_id_;
  std::vector<int>  els_tru_momid_;
  std::vector<int>  *p_els_tru_momid_;
  TBranch *b_els_tru_momid_;
  mutable bool c_els_tru_momid_;
  std::vector<int>  fjets15_btags_;
  std::vector<int>  *p_fjets15_btags_;
  TBranch *b_fjets15_btags_;
  mutable bool c_fjets15_btags_;
  std::vector<int>  fjets15_nconst_;
  std::vector<int>  *p_fjets15_nconst_;
  TBranch *b_fjets15_nconst_;
  mutable bool c_fjets15_nconst_;
  std::vector<int>  fsubjets_btags_;
  std::vector<int>  *p_fsubjets_btags_;
  TBranch *b_fsubjets_btags_;
  mutable bool c_fsubjets_btags_;
  std::vector<int>  fsubjets_nconst_;
  std::vector<int>  *p_fsubjets_nconst_;
  TBranch *b_fsubjets_nconst_;
  mutable bool c_fsubjets_nconst_;
  std::vector<int>  genfjets_nconst_;
  std::vector<int>  *p_genfjets_nconst_;
  TBranch *b_genfjets_nconst_;
  mutable bool c_genfjets_nconst_;
  std::vector<int>  genjets_genfjet_index_;
  std::vector<int>  *p_genjets_genfjet_index_;
  TBranch *b_genjets_genfjet_index_;
  mutable bool c_genjets_genfjet_index_;
  std::vector<int>  genjets_isr_code_;
  std::vector<int>  *p_genjets_isr_code_;
  TBranch *b_genjets_isr_code_;
  mutable bool c_genjets_isr_code_;
  std::vector<int>  jets_fjet15_index_;
  std::vector<int>  *p_jets_fjet15_index_;
  TBranch *b_jets_fjet15_index_;
  mutable bool c_jets_fjet15_index_;
  std::vector<int>  jets_isr_code_;
  std::vector<int>  *p_jets_isr_code_;
  TBranch *b_jets_isr_code_;
  mutable bool c_jets_isr_code_;
  std::vector<int>  mc_id_;
  std::vector<int>  *p_mc_id_;
  TBranch *b_mc_id_;
  mutable bool c_mc_id_;
  std::vector<int>  mc_status_;
  std::vector<int>  *p_mc_status_;
  TBranch *b_mc_status_;
  mutable bool c_mc_status_;
  std::vector<int>  mus_tru_id_;
  std::vector<int>  *p_mus_tru_id_;
  TBranch *b_mus_tru_id_;
  mutable bool c_mus_tru_id_;
  std::vector<int>  mus_tru_momid_;
  std::vector<int>  *p_mus_tru_momid_;
  TBranch *b_mus_tru_momid_;
  mutable bool c_mus_tru_momid_;
  std::vector<int>  subjets_fsubjet_index_;
  std::vector<int>  *p_subjets_fsubjet_index_;
  TBranch *b_subjets_fsubjet_index_;
  mutable bool c_subjets_fsubjet_index_;
  std::vector<int>  subjets_nsub_;
  std::vector<int>  *p_subjets_nsub_;
  TBranch *b_subjets_nsub_;
  mutable bool c_subjets_nsub_;
  std::vector<int>  tks_charge_;
  std::vector<int>  *p_tks_charge_;
  TBranch *b_tks_charge_;
  mutable bool c_tks_charge_;
  std::vector<int>  tks_from_pv_;
  std::vector<int>  *p_tks_from_pv_;
  TBranch *b_tks_from_pv_;
  mutable bool c_tks_from_pv_;
  std::vector<int>  tks_id_;
  std::vector<int>  *p_tks_id_;
  TBranch *b_tks_id_;
  mutable bool c_tks_id_;
  std::vector<int>  tks_num_prongs_;
  std::vector<int>  *p_tks_num_prongs_;
  TBranch *b_tks_num_prongs_;
  mutable bool c_tks_num_prongs_;
  std::vector<int>  tks_tru_id_;
  std::vector<int>  *p_tks_tru_id_;
  TBranch *b_tks_tru_id_;
  mutable bool c_tks_tru_id_;
  std::vector<size_t>  mc_mom_;
  std::vector<size_t>  *p_mc_mom_;
  TBranch *b_mc_mom_;
  mutable bool c_mc_mom_;
  unsigned  mc_type_;
  TBranch *b_mc_type_;
  mutable bool c_mc_type_;
};

#endif
